


// FORMATIONS
export const FETCH_FORMATIONS_REQUEST = "FETCH_FORMATIONS_REQUEST";
export const FETCH_FORMATIONS_SUCCESS = "FETCH_FORMATIONS_SUCCESS";
export const FETCH_FORMATIONS_SUCCESS_2 = "FETCH_FORMATIONS_SUCCESS_2";
export const FETCH_FORMATIONS_FAILURE = "FETCH_FORMATIONS_FAILURE";
// FORMATIONS LOADING
export const FETCH_FORMATION_REQUEST = "FETCH_FORMATION_REQUEST";
export const FETCH_FORMATION_SUCCESS = "FETCH_FORMATION_SUCCESS";
export const FETCH_FORMATION_FAILURE = "FETCH_FORMATION_FAILURE";


// LESSONS
export const FETCH_LESSONS_REQUEST = "FETCH_LESSONS_REQUEST";
export const FETCH_LESSONS_SUCCESS = "FETCH_LESSONS_SUCCESS";
export const FETCH_LESSONS_SUCCESS_2 = "FETCH_LESSONS_SUCCESS_2";
export const FETCH_LESSONS_FAILURE = "FETCH_LESSONS_FAILURE";
// LESSONS LOADING
export const FETCH_LESSON_REQUEST = "FETCH_LESSON_REQUEST";
export const FETCH_LESSON_SUCCESS = "FETCH_LESSON_SUCCESS";
export const FETCH_LESSON_FAILURE = "FETCH_LESSON_FAILURE";


// EXERCISES
export const FETCH_EXERCISES_REQUEST = "FETCH_EXERCISES_REQUEST";
export const FETCH_EXERCISES_SUCCESS = "FETCH_EXERCISES_SUCCESS";
export const FETCH_EXERCISES_SUCCESS_2 = "FETCH_EXERCISES_SUCCESS_2";
export const FETCH_EXERCISES_FAILURE = "FETCH_EXERCISES_FAILURE";
// EXERCISES LOADING
export const FETCH_EXERCISE_REQUEST = "FETCH_EXERCISE_REQUEST";
export const FETCH_EXERCISE_SUCCESS = "FETCH_EXERCISE_SUCCESS";
export const FETCH_EXERCISE_FAILURE = "FETCH_EXERCISE_FAILURE";



// MODULES
export const FETCH_MODULES_REQUEST = "FETCH_MODULES_REQUEST";
export const FETCH_MODULES_SUCCESS = "FETCH_MODULES_SUCCESS";
export const FETCH_MODULES_SUCCESS_2 = "FETCH_MODULES_SUCCESS_2";
export const FETCH_MODULES_FAILURE = "FETCH_MODULES_FAILURE";
// MODULES LOADING
export const FETCH_MODULE_REQUEST = "FETCH_MODULE_REQUEST";
export const FETCH_MODULE_SUCCESS = "FETCH_MODULE_SUCCESS";
export const FETCH_MODULE_FAILURE = "FETCH_MODULE_FAILURE";



// EXERCICE_PROGRES
export const FETCH_EXERCICE_PROGRESS_REQUEST = "FETCH_EXERCICE_PROGRESS_REQUEST";
export const FETCH_EXERCICE_PROGRESS_SUCCESS = "FETCH_EXERCICE_PROGRESS_SUCCESS";
export const FETCH_EXERCICE_PROGRESS_SUCCESS_2 = "FETCH_EXERCICE_PROGRESS_SUCCESS_2";
export const FETCH_EXERCICE_PROGRESS_FAILURE = "FETCH_EXERCICE_PROGRESS_FAILURE";
// EXERCICE_PROGRESS LOADING
export const FETCH_EXERCICE_PROGRES_REQUEST = "FETCH_EXERCICE_PROGRES_REQUEST";
export const FETCH_EXERCICE_PROGRES_SUCCESS = "FETCH_EXERCICE_PROGRES_SUCCESS";
export const FETCH_EXERCICE_PROGRES_FAILURE = "FETCH_EXERCICE_PROGRES_FAILURE";



// USERS
export const FETCH_USERSS_REQUEST = "FETCH_USERSS_REQUEST";
export const FETCH_USERSS_SUCCESS = "FETCH_USERSS_SUCCESS";
export const FETCH_USERSS_SUCCESS_2 = "FETCH_USERSS_SUCCESS_2";
export const FETCH_USERSS_FAILURE = "FETCH_USERSS_FAILURE";
// USERSS LOADING
export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";



export const FETCH_CONVERSATIONS_SEND = "FETCH_CONVERSATIONS_SEND";
export const FETCH_CONVERSATIONS_FAILURE = "FETCH_CONVERSATIONS_FAILURE"
//      chargement
export const SEND_REQUEST_CONVERSATION = "SEND_REQUEST_CONVERSATION";
export const REQUEST_SUCCESS_CONVERSATION = "REQUEST_SUCCESS_CONVERSATION";
export const REQUEST_FAILURE_CONVERSATION = "REQUEST_FAILURE_CONVERSATION";
// select
export const SELECT_USER_CONVERSATION = "SELECT_USER_CONVERSATION";















// TRADUCTION DE LA LANGUE ;
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export const changeLanguage = (language) => ({
  type: CHANGE_LANGUAGE,
  payload: language,
});